# Generated by Django 5.2.17 on 2026-09-08 07:40

import django.db.models.deletion
import django.utils.timezone
import modelsearch.index
import pages.models
import taggit.managers
import wagtail.fields
import wagtail.images.models
import wagtail.models.media
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(default="Notes from the workbench. Things I've built, lessons I've learned, and ideas I'm still figuring out.")),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CookbookIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(default="Good food has a way of bringing us home. A collection of Cajun family recipes from my grandfather's cookbook, Grandma's Mama's Recipes.")),
                ('story', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=40)),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.images.models.ImageFileMixin, modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(default='Family favorites', max_length=100)),
                ('introduction', models.TextField(blank=True)),
                ('servings', models.CharField(blank=True, max_length=100)),
                ('prep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cook_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('ingredients', models.TextField(help_text='One ingredient per line. Keep quantities and units together.')),
                ('instructions', models.TextField(help_text='One step per line. Steps are numbered automatically.')),
                ('notes', models.TextField(blank=True)),
                ('photo_alt', models.CharField(blank=True, max_length=250)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.siteimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='Developer. Maker. Home cook.', max_length=120)),
                ('headline', models.CharField(default='A little code.\nA lot of curiosity.', max_length=160)),
                ('introduction', models.TextField(default="I'm Jake Ardoin, an independent software developer, 3D-printing enthusiast, and pretty decent cook. This is where I share what I'm building, what I'm learning, and the recipes worth keeping.")),
                ('about', wagtail.fields.RichTextField(blank=True)),
                ('github_url', models.URLField(blank=True, default='https://github.com/GreatestJakeEVR')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.siteimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('introduction', models.CharField(max_length=300)),
                ('topic', models.CharField(default='Software development', max_length=60)),
                ('hero_alt', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('photo', 5), ('code', 8), ('quote', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for someone who cannot see it.'}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt_text', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Python', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('language', 6), ('code', 7)]], {}), 9: ('wagtail.blocks.BlockQuoteBlock', (), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.siteimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('file', models.ImageField(height_field='height', storage=pages.models.rendition_storage, upload_to='images', width_field='width')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='pages.siteimage')),
            ],
            options={
                'unique_together': {('image', 'filter_spec', 'focal_point_key')},
            },
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
    ]
