# Generated by Django 5.2.17 on 2026-09-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='source',
            field=models.CharField(blank=True, help_text='Cookbook or other source to credit, if applicable.', max_length=250),
        ),
    ]
